change model to json
fdanis/ygtrack pull request #2
Opened 2022-12-11 12:36 UTC by fdanis

2022-12-21 17:09 UTC, Bazys requested changes
есть что переделать

2022-12-21 17:09 UTC, Bazys commented on internal/server/store/filesync/filesync.go
> +func FileSync(app *config.AppConfig, ctx context.Context) {
контекст всегда первым аргументом в сигнатуре функции.
https://pkg.go.dev/context
и почем бы FileSync не сделать методом структуры AppConfig ?

2022-12-24 14:18 UTC, fdanis commented on cmd/agent/main.go
>  func Exit(cancel context.CancelFunc) {
хотел сделать выход из приложения по нажатию кнопки, удалил

2022-12-24 15:56 UTC, fdanis commented on cmd/agent/main.go
> +		if false {
исправил

2022-12-24 15:56 UTC, fdanis commented on cmd/server/main.go
> +var app config.AppConfig = config.AppConfig{}
все хотел попробовать и глобальные переменные тоже :) исправил

2022-12-24 15:56 UTC, fdanis commented on cmd/server/middleware.go
> +package main
готово

2022-12-24 15:57 UTC, fdanis commented on cmd/server/routes.go
> +package main
готово

2022-12-24 15:57 UTC, fdanis commented on internal/helpers/GzipPool.go
> +var Gzip GzipPool
сделал приватной

2022-12-24 15:57 UTC, fdanis commented on cmd/agent/main.go
> +type Conf struct {
вынес

2022-12-24 16:03 UTC, fdanis commented on cmd/agent/main.go
> +	hhelper := httphelper.Helper{}
сам не понял для чего GET метод нужен удалил. а ценность то что мы можем замокать этот объект в тестах

2022-12-24 16:03 UTC, fdanis commented on cmd/server/main.go
>  	server.ListenAndServe()
исправил

2022-12-24 16:03 UTC, fdanis commented on internal/server/handler/base.go
> +type malformedRequest struct {
исправил

2022-12-24 16:03 UTC, fdanis commented on internal/server/store/filesync/filesync.go
> +func FileSync(app *config.AppConfig, ctx context.Context) {
исправил

2022-12-26 12:58 UTC, Bazys commented on internal/server/handler/base.go
> +type malformedRequest struct {
внимательнее!
такие ошибки должны быть в формате `xxxError`

2022-12-26 13:22 UTC, Bazys requested changes

2022-12-26 13:22 UTC, Bazys commented on internal/server/handler/metrichandler.go
> +
зачем пустая строка?

2022-12-26 13:22 UTC, Bazys commented on internal/server/store/filesync/filesync.go
> +
зачем пустая строка?

2022-12-26 13:22 UTC, Bazys commented on internal/server/store/filesync/filesync.go
> +func Sync(fileName string, ch chan int, ctx context.Context, counterRepo repository.MetricRepository[int64], gaugeRepo repository.MetricRepository[float64]) {
опять контекст 3-им в списке аргументов функции?

2022-12-26 13:22 UTC, Bazys commented on internal/server/store/filesync/filesync.go
> +func SyncByInterval(ch chan int, ctx context.Context, interavl time.Duration) {
тоже контекст не первый

2022-12-26 13:22 UTC, Bazys commented on internal/helpers/httphelper/httphelper.go
> +func Post(url string, contentType string, data *bytes.Buffer) error {
все равно в принципе не понимаю смысла этого пакета?
тут одна функция, которая используется единственный раз во всем коде?
точно нужна?
может без неё обойтись?

2022-12-26 13:22 UTC, Bazys commented on internal/server/config/config.go
> +func (c *Environment) ReadEnv() error {
зачем возвращать ошибку, если ты ни разу её не проверяешь?

2022-12-26 13:22 UTC, Bazys commented on internal/server/config/config.go
> +		os.Mkdir(path.Dir(app.EnvConfig.StoreFile), 0777)
а если не удалось создать папку?

2022-12-26 13:22 UTC, Bazys commented on internal/server/store/filesync/filesync.go
> +	enc.Decode(&val)
а если формат кривой и ты не сможешь декодировать? как об этом узнаешь?

2022-12-26 20:52 UTC, fdanis commented on internal/server/store/filesync/filesync.go
> +	enc.Decode(&val)
исправил

2022-12-26 20:52 UTC, fdanis commented on internal/server/config/config.go
> +		os.Mkdir(path.Dir(app.EnvConfig.StoreFile), 0777)
исправил

2022-12-26 20:52 UTC, fdanis commented on internal/server/config/config.go
> +func (c *Environment) ReadEnv() error {
поправил

2022-12-26 20:53 UTC, fdanis commented on internal/helpers/httphelper/httphelper.go
> +func Post(url string, contentType string, data *bytes.Buffer) error {
удалил

2022-12-26 20:54 UTC, fdanis commented on internal/server/handler/metrichandler.go
> +
без понятия удалил

2022-12-26 20:54 UTC, fdanis commented on internal/server/store/filesync/filesync.go
> +
нервы наверно

2022-12-26 20:55 UTC, fdanis commented on internal/server/store/filesync/filesync.go
> +func Sync(fileName string, ch chan int, ctx context.Context, counterRepo repository.MetricRepository[int64], gaugeRepo repository.MetricRepository[float64]) {
больше не повторится

2022-12-26 20:55 UTC, fdanis commented on internal/server/store/filesync/filesync.go
> +func SyncByInterval(ch chan int, ctx context.Context, interavl time.Duration) {
исправил

2022-12-27 15:08 UTC, Bazys approved these changes

2022-12-27 21:06 UTC, merged