Increment9
fdanis/ygtrack pull request #3
Opened 2023-01-03 20:42 UTC by fdanis

2023-01-15 21:18 UTC, Bazys requested changes
Продолжаю восхищаться твоим решением с дженериками!
для совсем взрослого решения - прикрути мигратор (ссылка есть в коментах)

2023-01-15 21:18 UTC, Bazys commented on internal/agent/memstatservice/simplememstatservice_test.go
> +func (h *simpleMockHTTPHelper) Post(url string, header map[string]string, data *bytes.Buffer) error {
табличные тесты это классно!
теперь осталось добавить хотя бы по одному отрицательному сценарию в каждый.

2023-01-15 21:18 UTC, Bazys commented on internal/agent/memstatservice/simplememstatservice.go
> +func NewSimpleMemStatService(hashkey string) *SimpleMemStatService {
пакет называется memstatservice а основаня структура в нем SimpleMemStatService
давай как то синхрнизируем названия. Что бы была однозначная трактовка для чего модуль и что в нем происходит

2023-01-15 21:18 UTC, Bazys commented on internal/driver/driver.go
> +	CREATE TABLE IF NOT EXISTS public.countmetric (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(100),val bigint,created timestamp default now());
ты взрослый мальчик, может все таки какой то мигратор подключить?
1. https://github.com/golang-migrate/migrate
2. https://github.com/pressly/goose

2023-01-17 20:53 UTC, fdanis commented on cmd/agent/main.go
> +			//service.SendBatch("http://" + strings.TrimRight(host, "/") + "/updates/")
ок

2023-01-17 20:54 UTC, fdanis commented on internal/agent/memstatservice/simplememstatservice_test.go
> +func (h *simpleMockHTTPHelper) Post(url string, header map[string]string, data *bytes.Buffer) error {
добавил еще тест, но не могу придумать отрицательный

2023-01-17 20:54 UTC, fdanis commented on internal/agent/memstatservice/simplememstatservice.go
> +func NewSimpleMemStatService(hashkey string) *SimpleMemStatService {
назвал одинаково

2023-01-17 20:54 UTC, fdanis commented on internal/driver/driver.go
> +	CREATE TABLE IF NOT EXISTS public.countmetric (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(100),val bigint,created timestamp default now());
добавил миграцию

2023-01-19 07:44 UTC, Bazys approved these changes
остались вопросы на подумать.
Далее надо будет обрабатывать контекст в репозитории

2023-01-19 07:44 UTC, Bazys commented on cmd/agent/main.go
> +func Update(ctx context.Context, poolInterval time.Duration, service *memstatservice.MemStatService) {
выглядит как масло.Масляное
м.б. memstat.Service ?
это как предложение.

2023-01-19 07:44 UTC, Bazys commented on cmd/server/main.go
> +		Handler: server.Routes(&app, db),
всё таки я бы переименовал апп в конфиг.

2023-01-19 07:44 UTC, Bazys commented on cmd/server/main.go
> +	if db != nil {
на 38 строчку defer и не надо этого ифчика

2023-01-19 07:44 UTC, Bazys commented on internal/server/handler/metrichandler.go
> +func (h *MetricHandler) Ping(w http.ResponseWriter, r *http.Request) {
получается что хэндлер знает о БД только ради этого метода?
может обернуть и не хранить *sql.DB в хэндлере?

2023-01-22 20:39 UTC, merged